spring:
  application:
    name: lerning

  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT:5432}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: LerningHikariPool
      maximum-pool-size: ${PG_MAX_POOL:20}
      minimum-idle: ${PG_MIN_IDLE:5}
      connection-timeout: ${PG_CONN_TIMEOUT:30000}
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
